/**
 * Deterministic, non-AI feedback for the objective modules.
 *
 * Reading and Listening are graded against a stored answer key, so their
 * feedback is derived purely from the per-question outcome: which question
 * types were answered well and which need work. Nothing here is generated by
 * an AI provider and nothing is invented — every number comes from the graded
 * attempt.
 */
import type { QuestionType } from "@/lib/testing/types";
import type { AttemptResult } from "@/lib/testing/service";

export interface TypeBreakdownEntry {
  type: QuestionType;
  correct: number;
  total: number;
  /** 0..1, 0 when the type was not part of the test. */
  accuracy: number;
}

export interface ObjectiveFeedback {
  typeBreakdown: TypeBreakdownEntry[];
  /** Question types with accuracy >= threshold (strongest first). */
  strengths: TypeBreakdownEntry[];
  /** Question types with accuracy < threshold and at least one question. */
  weaknesses: TypeBreakdownEntry[];
  /** i18n keys under `testing.recommendations.*` for the weakest types. */
  recommendations: QuestionType[];
}

const STRENGTH_THRESHOLD = 0.7;
const WEAKNESS_THRESHOLD = 0.7;

/**
 * Build the feedback view. `review` is the graded attempt (server-side truth),
 * never a client-supplied score.
 */
export function buildObjectiveFeedback(result: Pick<AttemptResult, "review">): ObjectiveFeedback {
  const buckets = new Map<QuestionType, { correct: number; total: number }>();

  for (const item of result.review) {
    const bucket = buckets.get(item.type) ?? { correct: 0, total: 0 };
    bucket.total += 1;
    if (item.isCorrect) bucket.correct += 1;
    buckets.set(item.type, bucket);
  }

  const typeBreakdown: TypeBreakdownEntry[] = [];
  buckets.forEach((value, type) => {
    typeBreakdown.push({
      type,
      correct: value.correct,
      total: value.total,
      accuracy: value.total ? value.correct / value.total : 0,
    });
  });

  typeBreakdown.sort((a, b) => b.accuracy - a.accuracy || b.total - a.total);

  const strengths = typeBreakdown.filter((entry) => entry.accuracy >= STRENGTH_THRESHOLD);
  const weaknesses = typeBreakdown
    .filter((entry) => entry.accuracy < WEAKNESS_THRESHOLD)
    .sort((a, b) => a.accuracy - b.accuracy || b.total - a.total);

  return {
    typeBreakdown,
    strengths,
    weaknesses,
    recommendations: weaknesses.slice(0, 3).map((entry) => entry.type),
  };
}

/** Weakest section of the attempt (used for a one-line summary). */
export function weakestSection(
  result: Pick<AttemptResult, "scoresBySection">
): { title: string; correct: number; total: number } | null {
  if (result.scoresBySection.length === 0) return null;
  return [...result.scoresBySection].sort(
    (a, b) => a.correct / (a.total || 1) - b.correct / (b.total || 1)
  )[0];
}

/** Percentage helper shared by result UIs. */
export function accuracyPercent(correct: number, total: number): number {
  return total ? Math.round((correct / total) * 100) : 0;
}
