import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { getTranslations } from "next-intl/server";
import { Header } from "@/components/layout/Header";
import { Card } from "@/components/ui/Card";
import { FullExamAutoRefresh } from "@/components/full-exam/FullExamAutoRefresh";
import { getSession } from "@/lib/auth/session";
import { refreshFullExam } from "@/lib/full-exam/service";
import { listPublishedTests } from "@/lib/testing/service";
import { listSpeakingTests } from "@/lib/speaking/service";
const ORDER = ["listening", "reading", "writing", "speaking"] as const;
export default async function FullExamSessionPage(props: { params: Promise<{ id: string }> }) {
  const session = await getSession(); if (!session) redirect("/login"); const { id } = await props.params;
  const [t, exam, listeningTests, readingTests, speakingTests] = await Promise.all([getTranslations("fullExam"), refreshFullExam(session.userId, id), listPublishedTests("LISTENING"), listPublishedTests("READING"), listSpeakingTests()]); if (!exam) notFound();
  const tests = { listening: listeningTests[0]?.id ?? null, reading: readingTests[0]?.id ?? null, writing: "writing", speaking: speakingTests[0]?.id ?? null };
  const resultLinks = { listening: exam.components.listening.resultId ? `/listening/result/${exam.components.listening.resultId}` : null, reading: exam.components.reading.resultId ? `/reading/result/${exam.components.reading.resultId}` : null, writing: exam.components.writing.resultId ? `/writing/result/${exam.components.writing.resultId}` : null, speaking: exam.components.speaking.resultId ? `/speaking/result/${exam.components.speaking.resultId}` : null };
  const firstIncomplete = ORDER.findIndex((module) => exam.components[module].status !== "COMPLETED"); const processing = Object.values(exam.components).some((component) => component.status === "PROCESSING");
  return <div className="min-h-screen bg-gray-50"><FullExamAutoRefresh enabled={processing} /><Header /><main className="mx-auto max-w-5xl px-4 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand-600">{t("eyebrow")}</p><h1 className="mt-2 text-2xl font-extrabold text-gray-950">{exam.status === "COMPLETED" ? t("resultTitle") : t("sessionTitle")}</h1><p className="mt-1 text-sm text-gray-500">{t("startedAt")}: {new Date(exam.startedAt).toLocaleString()}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${exam.status === "COMPLETED" ? "bg-emerald-100 text-emerald-800" : exam.status === "FAILED" ? "bg-red-100 text-red-800" : "bg-amber-100 text-amber-800"}`}>{t(`status.${exam.status}`)}</span></div>
  {exam.status === "COMPLETED" && exam.overallBand != null ? <Card className="mt-6 bg-gradient-to-br from-brand-700 to-indigo-950 text-center text-white"><p className="text-sm font-semibold uppercase tracking-widest text-brand-200">{t("overall")}</p><p className="mt-3 text-7xl font-black">{exam.overallBand.toFixed(1)}</p><p className="mt-4 text-sm text-indigo-100">{t("officialRounding")}</p></Card> : null}
  <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{ORDER.map((module, index) => { const component = exam.components[module]; const canStart = exam.status !== "COMPLETED" && exam.status !== "FAILED" && index === firstIncomplete && component.status !== "PROCESSING"; const testId = tests[module]; const href = module === "writing" ? `/writing?fullExamId=${exam.id}` : testId ? `/${module}/${testId}?fullExamId=${exam.id}` : null; return <Card key={module} className={canStart ? "border-2 border-brand-400" : ""}><div className="flex items-center justify-between gap-3"><p className="font-semibold text-gray-950">{t(`modules.${module}`)}</p><span className="text-xs font-bold text-gray-500">{index + 1}/4</span></div><p className="mt-4 text-4xl font-extrabold text-gray-950">{component.band?.toFixed(1) ?? "—"}</p><p className="mt-1 text-xs text-gray-500">{t(`componentStatus.${component.status}`)}</p>{resultLinks[module] ? <Link href={resultLinks[module]!} className="mt-4 inline-block text-sm font-semibold text-brand-700 hover:underline">{t("viewResult")}</Link> : canStart && href ? <Link href={href} className="mt-4 inline-block rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white hover:bg-brand-700">{component.status === "FAILED" ? t("retry") : t("continue")}</Link> : canStart && !href ? <p className="mt-4 text-xs font-medium text-red-700">{t("testUnavailable")}</p> : null}</Card>; })}</div>
  {processing ? <Card className="mt-6 border-amber-200 bg-amber-50"><p className="font-semibold text-amber-900">{t("processingTitle")}</p><p className="mt-1 text-sm text-amber-800">{t("processingText")}</p></Card> : null}
  {exam.status === "COMPLETED" ? <Card className="mt-6"><h2 className="text-lg font-semibold text-gray-950">{t("focusTitle")}</h2><p className="mt-2 text-sm text-gray-700">{t("focusText", { modules: exam.weakestModules.map((module) => t(`modules.${module}`)).join(", ") })}</p><p className="mt-3 text-xs text-gray-500">{t("disclaimer")}</p></Card> : null}<Link href="/full-exam" className="mt-6 inline-block text-sm font-semibold text-brand-700 hover:underline">← {t("back")}</Link></main></div>;
}
